class ProductReferenceTunecoreSchema:
    ISRC_TC = "ISRC_TC"
    ISRC_OPTIONAL_TC = "ISRC_OPTIONAL_TC"
    TC_UPC = "TC_UPC"
    ID_SONG_SPOTIFY = "ID_SONG_SPOTIFY"
    ID_SONG_TC = "ID_SONG_TC"
    ID_ALBUM_TC = "ID_ALBUM_TC"
    TRACK_DURATION_IN_S_TC = "TRACK_DURATION_IN_S_TC"