from pyspark.sql.types import StructType, StructField, StringType, LongType, DateType, TimestampType, BooleanType, DecimalType, IntegerType, ArrayType
from src.constants.category_definition import Categories

class Schemas:
    PKID_DSP_RAW = "PKID_DSP_RAW"
    FKID_DP_PRODUCT = "FKID_DP_PRODUCT"
    ID_REPORT = "ID_REPORT"
    FKID_DISTRIBUTOR = "FKID_DISTRIBUTOR"
    FKID_DSP = "FKID_DSP"
    STREAM_DATE_DSP = "STREAM_DATE_DSP"
    FKID_STREAM_DATE = "FKID_STREAM_DATE"
    FKID_CLIENT_ACTION_DATE = "FKID_CLIENT_ACTION_DATE"
    UTC_TIMESTAMP_OFFSET_DSP = "UTC_TIMESTAMP_OFFSET_DSP"
    FKID_CLIENT_ACTION_TIME = "FKID_CLIENT_ACTION_TIME"
    CLIENT_ACTION_TIMESTAMP_DSP = "CLIENT_ACTION_TIMESTAMP_DSP"
    CLIENT_COUNTRY_DSP = "CLIENT_COUNTRY_DSP"
    FKID_CLIENT_COUNTRY = "FKID_CLIENT_COUNTRY"
    STREAM_COUNTRY_DSP = "STREAM_COUNTRY_DSP"
    FKID_STREAM_COUNTRY = "FKID_STREAM_COUNTRY"
    ISRC_DSP = "ISRC_DSP"
    TRACK_STORE_ID_DSP = "TRACK_STORE_ID_DSP"
    UPC_DSP = "UPC_DSP"
    FKID_CURRENCY = "FKID_CURRENCY"
    CURRENCY_DSP = "CURRENCY_DSP"
    CLIENT_AGE_BAND_DSP = "CLIENT_AGE_BAND_DSP"
    FKID_CLIENT_AGE_BAND = "FKID_CLIENT_AGE_BAND"
    CLIENT_CACHED_PLAY_DSP = "CLIENT_CACHED_PLAY_DSP"
    FKID_CLIENT_CACHED_PLAY = "FKID_CLIENT_CACHED_PLAY"
    CLIENT_DEVICE_DSP = "CLIENT_DEVICE_DSP"
    FKID_CLIENT_DEVICE = "FKID_CLIENT_DEVICE"
    CLIENT_GENDER_DSP = "CLIENT_GENDER_DSP"
    FKID_CLIENT_GENDER = "FKID_CLIENT_GENDER"
    ID_CLIENT_IDENTIFIER = "ID_CLIENT_IDENTIFIER"
    CLIENT_OFFER_DSP = "CLIENT_OFFER_DSP"
    FKID_CLIENT_OFFER = "FKID_CLIENT_OFFER"
    CLIENT_OS_DSP = "CLIENT_OS_DSP"
    FKID_CLIENT_OS = "FKID_CLIENT_OS"
    CLIENT_PARTNER_DSP = "CLIENT_PARTNER_DSP"
    FKID_CLIENT_PARTNER = "FKID_CLIENT_PARTNER"
    ORIGIN_SOURCE_STREAM_DSP = "ORIGIN_SOURCE_STREAM_DSP"
    FKID_ORIGIN_SOURCE_STREAM = "FKID_ORIGIN_SOURCE_STREAM"
    MUSIC_CONTAINER_NAME_DSP = "MUSIC_CONTAINER_NAME_DSP"
    MUSIC_CONTAINER_TYPE_DSP = "MUSIC_CONTAINER_TYPE_DSP"
    MUSIC_CONTAINER_ID_DSP = "MUSIC_CONTAINER_ID_DSP"
    FKID_MUSIC_CONTAINER_ID = "FKID_MUSIC_CONTAINER_ID"
    DSP_OFFER_DSP = "DSP_OFFER_DSP"
    FKID_DSP_OFFER = "FKID_DSP_OFFER"
    CONTENT_SUBTYPE_DSP = "CONTENT_SUBTYPE_DSP"
    FKID_CONTENT_SUBTYPE = "FKID_CONTENT_SUBTYPE"
    FKID_SALE_PRODUCT_TYPE = "FKID_SALE_PRODUCT_TYPE"
    AUDIO_FORMAT_DSP = "AUDIO_FORMAT_DSP"
    FKID_AUDIO_FORMAT = "FKID_AUDIO_FORMAT"
    QUANTITY = "QUANTITY"
    TOTAL_AMOUNT = "TOTAL_AMOUNT"
    WHOLEPRICE = "WHOLEPRICE"
    STREAM_PLAY_LENGTH = "STREAM_PLAY_LENGTH"
    TRACK_DURATION = "TRACK_DURATION"
    INSERT_TIMESTAMP = "INSERT_TIMESTAMP"
    UPDATE_TIMESTAMP = "UPDATE_TIMESTAMP"
    IS_DELETED = "IS_DELETED"
    STREAM_YEAR = "STREAM_YEAR"
    STREAM_MONTH = "STREAM_MONTH"
    STREAM_DAY = "STREAM_DAY"
    FIRST_TRACK_LISTENED = "FIRST_TRACK_LISTENED"
    PKID_DSP_SOCIAL_EVENT_RAW = "PKID_DSP_SOCIAL_EVENT_RAW"
    SOCIAL_EVENT_DATE_DSP = "SOCIAL_EVENT_DATE_DSP"
    FKID_SOCIAL_EVENT_DATE = "FKID_SOCIAL_EVENT_DATE"
    SOCIAL_EVENT_COUNTRY_DSP = "SOCIAL_EVENT_COUNTRY_DSP"
    FKID_SOCIAL_EVENT_COUNTRY = "FKID_SOCIAL_EVENT_COUNTRY"
    VIEWS_QUANTITY = "VIEWS_QUANTITY"
    COMMENTS_QUANTITY = "COMMENTS_QUANTITY"
    LIKES_QUANTITY = "LIKES_QUANTITY"
    SHARES_QUANTITY = "SHARES_QUANTITY"
    SOCIAL_EVENT_DAY = "SOCIAL_EVENT_DAY"
    SOCIAL_EVENT_MONTH = "SOCIAL_EVENT_MONTH"
    SOCIAL_EVENT_YEAR = "SOCIAL_EVENT_YEAR"
    FKID_VIDEO = "FKID_VIDEO"
    FKID_YOUTUBE_CHANNEL = "FKID_YOUTUBE_CHANNEL"
    ASSET_ID = "ASSET_ID"
    VIDEO_ID = "ASSET_ID"
    ASSET_ID_DSP = "ASSET_ID_DSP"
    CMS_TECHNICAL_NAME = "CMS_TECHNICAL_NAME"

    BLV_ERROR = "BLV_ERROR"
    BLV_MESSAGES = "BLV_MESSAGES"
    BLV_ERROR_CATEGORY = "BLV_ERROR_CATEGORY"

    INGESTION_MANDATORY_COLUMNS = [ID_REPORT, FKID_DSP, FKID_DISTRIBUTOR]

    CORRUPT_RECORD = "_corrupt_record"
    ID_STRUCTURING = "ID_STRUCTURING"
    RETRY_NUMBER = "RETRY_NUMBER"

    # Defined amount type
    AmountType = DecimalType(22, 8)

    # StructType for the STRUCTURING
    STRUCTURING = StructType([
        StructField(ID_REPORT, LongType(), False),
        StructField(FKID_DISTRIBUTOR, StringType(), False),
        StructField(FKID_DSP, StringType(), False),
        StructField(STREAM_DATE_DSP, DateType(), False),
        StructField(CLIENT_ACTION_TIMESTAMP_DSP, TimestampType(), False),
        StructField(UTC_TIMESTAMP_OFFSET_DSP, StringType(), True),
        StructField(CLIENT_COUNTRY_DSP, StringType(), True),
        StructField(STREAM_COUNTRY_DSP, StringType(), True),
        StructField(ISRC_DSP, StringType(), True),
        StructField(TRACK_STORE_ID_DSP, StringType(), True),
        StructField(UPC_DSP, StringType(), True),
        StructField(CURRENCY_DSP, StringType(), True),
        StructField(CLIENT_AGE_BAND_DSP, StringType(), True),
        StructField(CLIENT_CACHED_PLAY_DSP, StringType(), True),
        StructField(CLIENT_DEVICE_DSP, StringType(), True),
        StructField(CLIENT_GENDER_DSP, StringType(), True),
        StructField(ID_CLIENT_IDENTIFIER, StringType(), True),
        StructField(CLIENT_OFFER_DSP, StringType(), False),
        StructField(CLIENT_OS_DSP, StringType(), True),
        StructField(CLIENT_PARTNER_DSP, StringType(), True),
        StructField(ORIGIN_SOURCE_STREAM_DSP, StringType(), True),
        StructField(MUSIC_CONTAINER_NAME_DSP, StringType(), True),
        StructField(MUSIC_CONTAINER_TYPE_DSP, StringType(), True),
        StructField(MUSIC_CONTAINER_ID_DSP, StringType(), True),
        StructField(DSP_OFFER_DSP, StringType(), True),
        StructField(CONTENT_SUBTYPE_DSP, StringType(), True),
        StructField(QUANTITY, LongType(), True),
        StructField(STREAM_PLAY_LENGTH, AmountType, True),
        StructField(Categories.INGESTION_CATEGORY.error_col_name, BooleanType(), False),
        StructField(Categories.INGESTION_CATEGORY.error_message_name, ArrayType(StringType()), True),
        StructField(Categories.RAW_DATA_CATEGORY.error_col_name, BooleanType(), False),
        StructField(Categories.RAW_DATA_CATEGORY.error_message_name, ArrayType(StringType()), True),
        StructField(ID_STRUCTURING, LongType(), False),
        StructField(AUDIO_FORMAT_DSP, StringType(), True),
        StructField(FIRST_TRACK_LISTENED, IntegerType(), True)
    ])

    # StructType for the PIVOT
    PIVOT = StructType([
        StructField(PKID_DSP_RAW, StringType(), False),
        StructField(FKID_DP_PRODUCT, LongType(), False),
        StructField(ID_REPORT, LongType(), False),
        StructField(FKID_DISTRIBUTOR, StringType(), False),
        StructField(FKID_DSP, StringType(), False),
        StructField(STREAM_DATE_DSP, DateType(), False),
        StructField(FKID_STREAM_DATE, IntegerType(), False),
        StructField(STREAM_DAY, IntegerType(), False),
        StructField(STREAM_MONTH, IntegerType(), False),
        StructField(STREAM_YEAR, IntegerType(), False),
        StructField(FKID_CLIENT_ACTION_DATE, IntegerType(), True),
        StructField(FKID_CLIENT_ACTION_TIME, StringType(), True),
        StructField(UTC_TIMESTAMP_OFFSET_DSP, StringType(), True),
        StructField(CLIENT_ACTION_TIMESTAMP_DSP, TimestampType(), True),
        StructField(CLIENT_COUNTRY_DSP, StringType(), True),
        StructField(FKID_CLIENT_COUNTRY, IntegerType(), True),
        StructField(STREAM_COUNTRY_DSP, StringType(), True),
        StructField(FKID_STREAM_COUNTRY, IntegerType(), True),
        StructField(ISRC_DSP, StringType(), True),
        StructField(TRACK_STORE_ID_DSP, StringType(), True),
        StructField(UPC_DSP, StringType(), True),
        StructField(CURRENCY_DSP, StringType(), True),
        StructField(FKID_CURRENCY, StringType(), True),
        StructField(CLIENT_AGE_BAND_DSP, StringType(), True),
        StructField(FKID_CLIENT_AGE_BAND, IntegerType(), True),
        StructField(CLIENT_CACHED_PLAY_DSP, StringType(), True),
        StructField(FKID_CLIENT_CACHED_PLAY, IntegerType(), True),
        StructField(CLIENT_DEVICE_DSP, StringType(), True),
        StructField(FKID_CLIENT_DEVICE, IntegerType(), True),
        StructField(CLIENT_GENDER_DSP, StringType(), True),
        StructField(FKID_CLIENT_GENDER, IntegerType(), True),
        StructField(ID_CLIENT_IDENTIFIER, StringType(), True),
        StructField(CLIENT_OFFER_DSP, StringType(), True),
        StructField(FKID_CLIENT_OFFER, IntegerType(), True),
        StructField(CLIENT_OS_DSP, StringType(), True),
        StructField(FKID_CLIENT_OS, IntegerType(), True),
        StructField(CLIENT_PARTNER_DSP, StringType(), True),
        StructField(FKID_CLIENT_PARTNER, IntegerType(), True),
        StructField(ORIGIN_SOURCE_STREAM_DSP, StringType(), True),
        StructField(FKID_ORIGIN_SOURCE_STREAM, IntegerType(), True),
        StructField(MUSIC_CONTAINER_NAME_DSP, StringType(), True),
        StructField(MUSIC_CONTAINER_TYPE_DSP, StringType(), True),
        StructField(MUSIC_CONTAINER_ID_DSP, StringType(), True),
        StructField(FKID_MUSIC_CONTAINER_ID, IntegerType(), True),
        StructField(DSP_OFFER_DSP, StringType(), True),
        StructField(FKID_DSP_OFFER, IntegerType(), True),
        StructField(CONTENT_SUBTYPE_DSP, StringType(), True),
        StructField(FKID_CONTENT_SUBTYPE, IntegerType(), True),
        StructField(FKID_SALE_PRODUCT_TYPE, IntegerType(), True),
        StructField(AUDIO_FORMAT_DSP, StringType(), True),
        StructField(FKID_AUDIO_FORMAT, IntegerType(), True),
        StructField(QUANTITY, LongType(), True),
        StructField(TOTAL_AMOUNT, AmountType, True),
        StructField(WHOLEPRICE, AmountType, True),
        StructField(STREAM_PLAY_LENGTH, AmountType, True),
        StructField(TRACK_DURATION, AmountType, True),
        StructField(INSERT_TIMESTAMP, TimestampType(), False),
        StructField(UPDATE_TIMESTAMP, TimestampType(), False),
        StructField(IS_DELETED, BooleanType(), True),
        StructField(FIRST_TRACK_LISTENED, IntegerType(), True)
    ])
