class MetricsDefinition:
    RAW_DATA = "RAW_DATA"
    INVALID_RAW_DATA = "INVALID_RAW_DATA"
    USEFUL_RAW_DATA = "USEFUL_RAW_DATA"
    FINAL_RAW_DATA = "FINAL_RAW_DATA"
    INGESTED_DATA = "INGESTED_DATA"
    RAW_DATA_METRICS = "RAW_DATA_METRICS"
    USEFUL_RAW_DATA_METRICS = "USEFUL_RAW_DATA_METRICS"
    FINAL_RAW_DATA_METRICS = "FINAL_RAW_DATA_METRICS"