class Dsp:
    SPOTIFY = "spotify"
    NETEASE = "netease"
    VK = "vk"
    DEEZER = "deezer"
    NAPSTER = "napster"
    ITUNES = "itunes"
    APPLE_MUSIC = "apple-music"
    APPLE_MUSIC_LIBRARY = "apple-music-library"
    APPLE_MUSIC_DEMO = "apple-music-demo"
    APPLE_MUSIC_CONTAINER = "apple-music-container"
    YOUTUBE = "youtube"
    YOUTUBE_ENGAGEMENT = "youtube-engagement"
    TIKTOK = "tiktok"
    DOUYIN = "douyin"